### ISSUE TITLE
Create/find launch icon for app

### ISSUE THREAD

**Issue by mikeng13** [FinNerds/AndroidApp#46]
- [x] Launch icon
- [x] Notification icon

**Comment by styliii** [comment]
Green background
White W, that looks jagged like an ascending chart....maybe an arrow at the end of the chart

**Comment by mikeng13** [comment]
This is what my wife and I came up with: 

![logo converted -arrow-2](https://cloud.githubusercontent.com/assets/1365958/6991655/13ae2804-da56-11e4-889f-407454bbb2be.png)
