### ISSUE TITLE
Yahoo finance doesn't have access to ^DJI

### ISSUE THREAD

**Issue by mikeng13** [FinNerds/AndroidApp#50]
Looks like there are legal issues with yahoo finance providing data for the Dow Jones index. We need a workaround for this.

**Comment by styliii** [comment]
Dow Jones ETF?
https://www.spdrs.com/product/fund.seam?ticker=DIA

**Comment by mikeng13** [comment]
It is similar, but it can be a bit confusing to see 170 vs 17000 (which most ppl expect dow to be in the 10ks)
