### ISSUE TITLE
Make homescreen watchlist stocks update "live"

### ISSUE THREAD

**Issue by enginnerd** [FinNerds/AndroidApp#61]

**Comment by enginnerd** [comment]
if user is on this screen keep updating stock values? make it seems cool and real-time

**Comment by mikeng13** [comment]
every minute? We can add another background task :)

**Comment by enginnerd** [comment]
maybe even faster (we could add a dial somewhere for a user to adjust it in a settings pane)

**Comment by mikeng13** [comment]
the only prob is that Yahoo has rate limits per IP address so I don't want our user to get banned. 

It's capped at 2000/hr/ip, which is actually not bad

**Comment by enginnerd** [comment]
ah, make sense then

**Comment by mikeng13** [comment]
This is done. I put in 5 secs as the temp interval. We can always lower it later.
