### ISSUE TITLE
Style the detail view

### ISSUE THREAD

**Issue by mikeng13** [FinNerds/AndroidApp#68]

**Comment by styliii** [comment]
- change chart colors (make it sexy)
- for numbers that are off the screen, dynamically resize?
- do not show ad ex-dividend date, if there is none
- change color of alarm bell if alert exists or checkbox on alarm bell

**Comment by styliii** [comment]
https://dribbble.com/shots/819236-Simple-Stocks-Stats?list=searches&tag=chart&offset=27
